name: Pull Request Code Security Check

on:
  pull_request:
    branches: [main]

jobs:
  pr-blocker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit Security Check
      run: bandit -r . -x tests

    - name: Fail PR if security issues found
      run: |
        bandit -r . -x tests -f json -o bandit-results.json
        cat bandit-results.json
        issues=$(jq '.results | length' bandit-results.json)
        if [ "$issues" -gt 0 ]; then
          echo "::error ::Bandit found $issues security issue(s). Please fix them before merging."
          exit 1
        fi
